apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: drplan-eks-singapore
  region: ap-southeast-1
  version: "1.29"

vpc:
  id: vpc-04ce64a01d4e09266
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-0eb3d0a10ccd1b4c5
      ap-northeast-2c:
        id: subnet-0e250268ead65af75

managedNodeGroups:
  - name: drplan-ng-singapore
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: singapore
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true
        autoScaler: true
        imageBuilder: true

